-- O schema operacional agora é PostgreSQL e evolui por migrations versionadas.
-- A fonte canônica inicial está em:
-- server/database/migrations/001_core_entities.sql
--
-- Execute com:
-- npm run db:migrate
--
-- Este arquivo permanece apenas como ponte para quem conhecia o schema legado.
